version: '3.4'

services:

  api:
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ServiceEndpoints__VoskKaldiRu=ws://kaldi.ru.websocket:2700/
    image: ${DOCKER_REGISTRY-}speechapi
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - kaldi.ru.websocket
    ports:
      - 80:80
      - 443:443
    volumes:
      - C:/Users/ximlr/.aspnet/https:/https/  

  kaldi.ru.websocket:
    container_name: kaldi.ws
    image: alphacep/kaldi-ru:latest    